### ISSUE TITLE
module 'get_filesystem' error

### ISSUE THREAD

**Issue by Chaanigim** [pytorch/tutorials#1919]
[PyTorch TensorBoard Support](https://pytorch.org/tutorials/beginner/introyt/tensorboardyt_tutorial.html)
In this tutorials, Error Occurred

**Error**
AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'

**Solution: Add the below code to get 'get_filesystem'**
import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile

cc @aaronenyeshi @chaekit @robieta

**Comment by Chaanigim** [comment]
In order to display the tensor board window, you must run through the command below in bash. 

tensorboard --logdir=runs 
and open a browser tab to http://localhost:6006/

In order to export tensorflow to the network during Run, the proxy or command pass –bind all must be used, but the process does not proceed smoothly. A simple solution without using the bash command and doing any specific work is to extend and load the tensor board from the nose lab and float it on the nose lab itself.

**solution : Replace with the code below**
%load_ext tensorboard
%tensorboard --logdir runs --port=6006

**Comment by malfet** [comment]
Thank you for reporting the issue, this one seems related: https://github.com/pytorch/pytorch/issues/30966

**Comment by malfet** [comment]
Adding backtrace from the Collab notebook:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-cff6eb059fb9>](https://localhost:8080/#) in <module>()
     16 writer.add_embedding(features,
     17                     metadata=class_labels,
---> 18                     label_img=images.unsqueeze(1))
     19 writer.flush()
     20 writer.close()

[/usr/local/lib/python3.7/dist-packages/torch/utils/tensorboard/writer.py](https://localhost:8080/#) in add_embedding(self, mat, metadata, label_img, global_step, tag, metadata_header)
    808         save_path = os.path.join(self._get_file_writer().get_logdir(), subdir)
    809 
--> 810         fs = tf.io.gfile.get_filesystem(save_path)
    811         if fs.exists(save_path):
    812             if fs.isdir(save_path):

AttributeError: module 'tensorflow._api.v2.io.gfile' has no attribute 'get_filesystem'
```

**Comment by ppwwyyxx** [comment]
Should be fixed by https://github.com/pytorch/pytorch/pull/89832

**Comment by svekars** [comment]
Still an issue. Can try the suggested temporary solution:
```
import tensorflow as tf
import tensorboard as tb
tf.io.gfile = tb.compat.tensorflow_stub.io.gfile
``` 
Can maybe add this to the doc for now.

**Comment by zabboud** [comment]
\assigntome
